version: '3' 

services: 
  mysql: 
    image: mysql:5.7 
    ports: 
      - 3306:3306
    volumes: 
      - ./data/mysql/data:/var/lib/mysql:rw
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    container_name: mysql
    restart: always
    command:
      - mysqld
      - --default-time-zone=Asia/Shanghai
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0
    command: redis-server /usr/local/etc/redis/redis.conf 
    restart: always 
    container_name: redis
    ports: 
      - 6379:6379 
    volumes: 
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./data/redis/data:/data:rw
